resources:
- bases/external-secrets.io_clustersecretstores.yaml
- bases/external-secrets.io_secretstores.yaml
- bases/external-secrets.io_externalsecrets.yaml

patchesStrategicMerge:
- patches/webhook_in_externalsecrets.yaml
- patches/webhook_in_clustersecretstores.yaml
- patches/webhook_in_secretstores.yaml

configurations: []