apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example
spec:
  provider:
    oracle: #Needs to match value in secretstore_types.go
      user: "**User OCID**"
      tenancy: "**Tenancy OCID**"
      region: "**Region**"
      auth:
        secretRef:
          privatekey:
            name: oracle-secret
            key: privateKey #Needs to match stringData val in secret_oracle.yml
          fingerprint:
            name: oracle-secret
            key: fingerprint