apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret
  labels: 
    type: oracle
type: Opaque
stringData:
  privateKey: "**Private key value**, use |- for multiline"
  fingerprint: "**Fingerprint value**"