# permissions for end users to view secretstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretstore-viewer-role
rules:
- apiGroups:
  - external-secrets.x-k8s.io
  resources:
  - secretstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - external-secrets.x-k8s.io
  resources:
  - secretstores/status
  verbs:
  - get
