apiVersion: external-secrets.x-k8s.io/v1alpha1
kind: ExternalSecret
metadata:
  name: externalsecret-sample
spec:
  secretStoreRef:
    name: secretstore-sample

  target:
    name: secret-to-be-created
    creationPolicy: Owner

  refreshInternal: 1h

  data:
  - secretKey: secret-key-to-be-created
    remoteRef:
      key: remote-key-in-the-provider
      version: remote-version-in-the-provider

  dataFrom:
  - remoteRef:
      key: remote-key-in-the-provider
