apiVersion: external-secrets.x-k8s.io/v1alpha1
kind: ExternalSecret
metadata:
  name: externalsecret-sample
spec:
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore

  target:
    name: secret-to-be-created
    creationPolicy: Owner

  refreshInternal: 1h

  data:
  - secretKey: secret-key-to-be-managed
    remoteRef:
      key: provider-key
      version: provider-key-version
      property: provider-key-property

  dataFrom:
  - remoteRef:
      key: remote-key-in-the-provider
