apiVersion: external-secrets.x-k8s.io/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  controller: dev

  awssm:
    auth:
      secretRef:
        accessKeyID:
          name: awssm-secret
          key: access-key

        secretAccessKey:
          name: awssm-secret
          key: secret-access-key

    role: iam-role
    region: eu-central-1
