{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-secrets.name" . }}-webhook
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
    external-secrets.io/component : conversion-webhook
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: webhook
  selector:
    {{- include "external-secrets.selectorLabels" . | nindent 4 }}
{{- end }}
