apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-secrets.fullname" . }}-webhook
  labels:
    {{- include "external-secrets-webhook.labels" . | nindent 4 }}
    external-secrets.io/component : webhook
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: webhook
    - port: {{ .Values.webhook.prometheus.service.port}}
      targetPort: {{ .Values.webhook.prometheus.service.port}}
      protocol: TCP
      name: metrics
  selector:
    {{- include "external-secrets-webhook.selectorLabels" . | nindent 4 }}
